steps:
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      - "functions"
      - "deploy"
      - "redeploy_model"
      - "--runtime=python310"
      - "--trigger-event=google.storage.object.finalize"
      - "--entry-point=redeploy_model"

  - name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "-t"
      - "gcr.io/$PROJECT_ID/training-image"
      - "."
      
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      - "ai"
      - "custom-jobs"
      - "create"
      - "--region=us-central1"
      - "--display-name=training-job"
      - "--python-package-uris=gs://$PROJECT_ID/training-package.tar.gz"
      - "--python-module=trainer.train"
      - "--args=--batch_size=32,--learning_rate=0.01"